// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action ExitAction;
    
    private Gtk.Action SaveResultsAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Label lblProposition;
    
    private Gtk.Image imgTest;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Button cmdStart;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("Exit"), null, null);
        this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w1.Add(this.ExitAction, null);
        this.SaveResultsAction = new Gtk.Action("SaveResultsAction", Mono.Unix.Catalog.GetString("Save results"), null, null);
        this.SaveResultsAction.ShortLabel = Mono.Unix.Catalog.GetString("Save results");
        w1.Add(this.SaveResultsAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Events = ((Gdk.EventMask)(268));
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Cognitive dynamics test");
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        this.Resizable = false;
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='SaveResultsAction' action='SaveResultsAction'/><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.lblProposition = new Gtk.Label();
        this.lblProposition.Name = "lblProposition";
        this.lblProposition.LabelProp = Mono.Unix.Catalog.GetString(" ");
        this.lblProposition.Wrap = true;
        this.lblProposition.Justify = ((Gtk.Justification)(2));
        this.vbox1.Add(this.lblProposition);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.lblProposition]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.imgTest = new Gtk.Image();
        this.imgTest.CanFocus = true;
        this.imgTest.Events = ((Gdk.EventMask)(260));
        this.imgTest.Name = "imgTest";
        this.vbox1.Add(this.imgTest);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.imgTest]));
        w4.Position = 2;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.cmdStart = new Gtk.Button();
        this.cmdStart.CanFocus = true;
        this.cmdStart.Name = "cmdStart";
        this.cmdStart.UseUnderline = true;
        this.cmdStart.Label = Mono.Unix.Catalog.GetString("Start");
        this.hbox1.Add(this.cmdStart);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.cmdStart]));
        w5.Position = 1;
        w5.Expand = false;
        w5.Fill = false;
        w5.Padding = ((uint)(200));
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w6.Position = 3;
        w6.Expand = false;
        w6.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 475;
        this.DefaultHeight = 337;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.MotionNotifyEvent += new Gtk.MotionNotifyEventHandler(this.OnMotionNotifyEvent);
        this.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnButtonPressEvent);
        this.ExitAction.Activated += new System.EventHandler(this.OnExitActionActivated);
        this.SaveResultsAction.Activated += new System.EventHandler(this.OnSaveResultsActionActivated);
        this.imgTest.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnImgTestButtonPressEvent);
        this.cmdStart.Clicked += new System.EventHandler(this.OnCmdStartClicked);
    }
}
